global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

#  - job_name: 'myapp'
#    static_configs:
#      - targets: ['myapp:8080']